### PR TITLE
Enabling ppc64le

### PR DESCRIPTION
**Pull request by junawaneshivani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by junawaneshivani** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
You need to decrease parallelism on `ppc64le` as the ratio of RAM/core is much lower than on other platforms.

**Comment by junawaneshivani** [comment]
@xhochy which file do I exactly need to edit to decrease parallelism on ppc64le ?

**Comment by xhochy** [comment]
Do a special casing of https://github.com/conda-forge/libv8-feedstock/blob/27f9ef359400e3ec29a6a860a011d060c7d78d8f/recipe/build.sh#L78 for `ppc64le` where it only uses 2 CPUs or so

**Comment by junawaneshivani** [comment]
@xhochy please review.

**Comment by xhochy** [comment]
> @xhochy please review.

CI is still red.

**Comment by junawaneshivani** [comment]
> > @xhochy please review.
> 
> CI is still red.

Yes logs show `The job exceeded the maximum time limit for jobs, and has been terminated.`  May be increasing the no. of parallel job limit should help.

**Pull request closed without merging**
